from __future__ import annotations

"""
Central pathology-related constants.

Keeping these in a dedicated module avoids bloating `views.py` and makes the
educational content reusable in templates/APIs without importing view code.
"""

from django.utils.translation import gettext_lazy as _

# Educational pathology explanations shown on the results page.
# Values are lazy translation objects (evaluated per-request locale).
PATHOLOGY_EXPLANATIONS = {
    'Atelectasis': _('Atelectasis refers to the collapse or incomplete expansion of lung tissue, resulting in reduced gas exchange. It can be caused by airway obstruction (resorption atelectasis), external compression of the lung (compressive atelectasis), or insufficient surfactant production. Common causes include mucus plugging, foreign bodies, tumors, pneumothorax, pleural effusion, and post-surgical complications. On chest X-rays, atelectasis appears as areas of increased opacity with volume loss, often accompanied by compensatory changes such as mediastinal shift, elevated hemidiaphragm, or rib crowding.'),
    'Cardiomegaly': _('Cardiomegaly refers to enlargement of the heart, typically identified on chest X-rays when the cardiothoracic ratio exceeds 0.50 on a posteroanterior (PA) view. It can result from various conditions including hypertension, heart failure, cardiomyopathy, valvular disease, or congenital heart defects. The enlarged cardiac silhouette may appear globular or have specific chamber enlargement patterns depending on the underlying cause. Cardiomegaly often indicates underlying cardiovascular disease and may require further evaluation with echocardiography or other cardiac imaging.'),
    'Consolidation': _('Consolidation represents the filling of alveolar spaces with fluid, pus, blood, or other material, replacing normal air-filled lung tissue. It appears as homogeneous opacity on chest X-rays, often with air bronchograms visible within the consolidated area. Common causes include pneumonia (bacterial, viral, or fungal), pulmonary edema, hemorrhage, or aspiration. The opacity typically has well-defined borders and may be lobar, segmental, or patchy in distribution. Clinical correlation is essential for determining the underlying cause and appropriate treatment.'),
    'Edema': _('Pulmonary edema is the accumulation of excess fluid in the lung tissue and alveolar spaces, resulting in impaired gas exchange. It can be cardiogenic (due to heart failure, valve disease, or fluid overload) or non-cardiogenic (due to acute lung injury, infection, or capillary leak). On chest X-rays, pulmonary edema appears as bilateral, symmetrical opacities that may have a "bat wing" or perihilar distribution. Additional findings may include cardiomegaly, pleural effusions, and prominent pulmonary vasculature. Early recognition is crucial as it can be life-threatening.'),
    'Effusion': _('Pleural effusion is the abnormal accumulation of fluid in the pleural space between the lung and chest wall. It can be transudative (due to heart failure, liver disease, or kidney disease) or exudative (due to infection, malignancy, or inflammatory conditions). On chest X-rays, pleural effusion appears as a homogeneous opacity that obscures the diaphragm and costophrenic angle, with a meniscus sign at the fluid-air interface. Large effusions can cause mediastinal shift away from the affected side and require drainage for both diagnostic and therapeutic purposes.'),
    'Emphysema': _('Emphysema is a chronic obstructive pulmonary disease characterized by permanent enlargement and destruction of alveolar spaces distal to terminal bronchioles. It is most commonly caused by smoking but can also result from alpha-1 antitrypsin deficiency or occupational exposures. On chest X-rays, emphysema appears as hyperinflation with flattened hemidiaphragms, increased anteroposterior diameter, and decreased lung markings. Advanced cases may show bullae formation and signs of pulmonary hypertension. High-resolution CT is more sensitive for detecting early emphysematous changes.'),
    'Fibrosis': _('Pulmonary fibrosis involves the thickening and scarring of lung tissue, leading to progressive loss of lung function. It can be idiopathic or secondary to various causes including occupational exposures (asbestosis, silicosis), medications, radiation therapy, or connective tissue diseases. On chest X-rays, fibrosis appears as reticular or reticulonodular opacities, often with a lower lobe predominance. Advanced cases may show honeycombing, traction bronchiectasis, and loss of lung volume. Early detection and treatment are important to slow disease progression.'),
    'Hernia': _('Hiatal hernia occurs when part of the stomach protrudes through the diaphragmatic opening into the thoracic cavity. It can be sliding (most common) or paraesophageal (less common but more serious). On chest X-rays, hiatal hernia may appear as a retrocardiac mass or air-fluid level behind the heart. Large hernias can compress adjacent structures and may be associated with complications such as gastric volvulus, obstruction, or strangulation. Barium studies or CT imaging may be needed for detailed evaluation.'),
    'Infiltration': _('Pulmonary infiltration refers to the abnormal accumulation of substances in lung tissue, including inflammatory cells, fluid, or other materials. It appears as areas of increased opacity on chest X-rays and can be caused by various conditions such as pneumonia, pulmonary edema, hemorrhage, or interstitial lung disease. The pattern and distribution of infiltrates can help narrow the differential diagnosis. Infiltrates may be patchy, diffuse, or have specific patterns like ground-glass opacity or crazy-paving pattern on high-resolution imaging.'),
    'Mass': _('A pulmonary mass is a focal opacity greater than 3 cm in diameter that appears on chest imaging. Masses can be benign (such as hamartomas or granulomas) or malignant (primary lung cancer or metastases). On chest X-rays, masses appear as well-defined or spiculated opacities that may be accompanied by additional findings such as pleural effusion, lymphadenopathy, or bone lesions. Further evaluation with CT imaging, PET scanning, and tissue sampling is typically required to determine the nature and extent of the mass.'),
    'Nodule': _('A pulmonary nodule is a focal opacity less than or equal to 3 cm in diameter surrounded by normal lung tissue. Nodules can be solitary or multiple and may be benign (granulomas, hamartomas) or malignant (primary or metastatic cancer). On chest X-rays, nodules appear as rounded opacities that may be calcified or non-calcified. The size, morphology, and growth rate of nodules help determine the need for further evaluation. CT imaging is often required for detailed characterization and follow-up.'),
    'Pleural Thickening': _('Pleural thickening involves the abnormal thickening of the pleural membranes surrounding the lungs, which can be focal or diffuse. It may result from previous infection (empyema, tuberculosis), asbestos exposure, trauma, or malignancy. On chest X-rays, pleural thickening appears as increased opacity along the pleural surfaces, often with blunting of the costophrenic angles. Extensive pleural thickening can restrict lung expansion and cause respiratory symptoms. High-resolution CT is more sensitive for detecting subtle pleural abnormalities and assessing disease extent.'),
    'Pneumonia': _('Pneumonia is an inflammatory condition of the lung tissue, usually caused by bacterial, viral, or fungal infections. It can also result from aspiration or chemical irritants. On chest X-rays, pneumonia appears as areas of consolidation or infiltration that may be lobar, segmental, or patchy in distribution. Air bronchograms are often visible within the consolidated areas. Clinical symptoms include fever, cough, shortness of breath, and chest pain. Prompt diagnosis and appropriate antibiotic therapy are essential for optimal outcomes.'),
    'Pneumothorax': _('Pneumothorax is the presence of air in the pleural space, causing partial or complete lung collapse. It can be spontaneous (primary in healthy individuals or secondary in those with lung disease) or traumatic (due to injury or medical procedures). On chest X-rays, pneumothorax appears as a lucent area without lung markings, with a visible pleural line separating the collapsed lung from the chest wall. Large pneumothoraces may cause mediastinal shift and require immediate decompression. Small pneumothoraces may resolve spontaneously with observation.'),
    'Fracture': _('Rib fractures are breaks in one or more of the bones that form the ribcage, commonly resulting from trauma, falls, or repetitive stress. On chest X-rays, fractures may appear as lucent lines, discontinuity of the cortex, or displacement of bone fragments. Multiple rib fractures can be associated with serious complications including pneumothorax, hemothorax, or injury to underlying organs. Pathological fractures may occur in patients with bone metastases or metabolic bone disease. Pain management and monitoring for complications are important aspects of treatment.'),
    'Lung Opacity': _('Lung opacity refers to any area of increased density on chest imaging that obscures normal lung anatomy. It is a general term that encompasses various pathological processes including consolidation, ground-glass opacity, or mass lesions. The pattern, distribution, and associated findings help narrow the differential diagnosis. Common causes include pneumonia, pulmonary edema, interstitial lung disease, or malignancy. Further evaluation with high-resolution CT imaging and clinical correlation is often needed to determine the specific underlying pathology.'),
    'Enlarged Cardiomediastinum': _('Enlarged cardiomediastinum refers to an increase in the combined width of the cardiac silhouette and mediastinal contours. On a standard posteroanterior (PA) view, it is commonly identified when the cardiothoracic ratio (maximum horizontal cardiac diameter divided by maximal thoracic diameter) exceeds 0.50. On an anteroposterior (AP) projection—often performed in supine or portable studies—a mediastinal width greater than approximately 6–8 cm at the level of the aortic knob likewise suggests enlargement. Common causes include: Cardiomegaly (e.g., dilated cardiomyopathy, left ventricular hypertrophy), Pericardial effusion, which produces a globular ("water‐bottle") silhouette, Aortic pathology (aneurysm or dissection) leading to mediastinal widening, Mediastinal masses or lymphadenopathy. Recognition of an enlarged cardiomediastinum is pivotal, as it often prompts further evaluation—such as echocardiography for cardiac enlargement or contrast-enhanced CT to assess aortic and mediastinal pathology.'),
    'Lung Lesion': _('A lung lesion is any abnormal area or growth in lung tissue that differs from normal lung anatomy. Lesions can be benign or malignant and may include nodules, masses, cysts, or areas of inflammation. On chest X-rays, lesions appear as focal opacities that may vary in size, shape, and density. The characteristics of the lesion, including its borders, calcification pattern, and growth rate, help determine the likelihood of malignancy. Further evaluation with CT imaging, PET scanning, and possibly tissue sampling is often required to establish a definitive diagnosis and guide appropriate treatment.'),
}

