version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: mcads_db
    environment:
      POSTGRES_DB: mcads_db
      POSTGRES_USER: mcads_user
      POSTGRES_PASSWORD: mcads_secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcads_user -d mcads_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Celery and caching
  redis:
    image: redis:7-alpine
    container_name: mcads_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Web Application
  web:
    build: .
    container_name: mcads_web
    entrypoint: []
    command: bash -c "
      echo 'Starting MCADS Docker initialization...' &&
      while ! pg_isready -h db -p 5432 -U mcads_user; do sleep 2; done &&
      while ! redis-cli -h redis ping > /dev/null 2>&1; do sleep 2; done &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      mkdir -p /app/logs /app/media /app/data_exports /app/backups &&
      echo 'MCADS initialization completed!' &&
      gunicorn --bind 0.0.0.0:8000 --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 60 --max-requests 1000 --access-logfile /app/logs/gunicorn_access.log --error-logfile /app/logs/gunicorn_error.log mcads_project.asgi:application"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SECRET_KEY=mcads-production-key-2024-xray-deployment-server-secure-key-hashes
      - DEBUG=False
      - DB_NAME=mcads_db
      - DB_USER=mcads_user
      - DB_PASSWORD=mcads_secure_password_2024
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,mcads.casa,www.mcads.casa,203.161.58.22,server1.mcads.casa
      - TORCH_HOME=/app/.torch
      - TORCHXRAYVISION_CACHE_DIR=/app/.torchxrayvision
      - XRV_DATA_DIR=/app/.torchxrayvision
      - MPLCONFIGDIR=/app/.matplotlib
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./logs:/app/logs
      - ./data_exports:/app/data_exports
      - ./backups:/app/backups
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-L", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker for async tasks
  celery:
    build: .
    container_name: mcads_celery
    entrypoint: []
    command: bash -c "
      while ! pg_isready -h db -p 5432 -U mcads_user; do sleep 2; done &&
      while ! redis-cli -h redis ping > /dev/null 2>&1; do sleep 2; done &&
      celery -A mcads_project worker -l info --concurrency=1"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SECRET_KEY=mcads-production-key-2024-xray-deployment-server-secure-key-hashes
      - DEBUG=False
      - DB_NAME=mcads_db
      - DB_USER=mcads_user
      - DB_PASSWORD=mcads_secure_password_2024
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - TORCH_HOME=/app/.torch
      - TORCHXRAYVISION_CACHE_DIR=/app/.torchxrayvision
      - XRV_DATA_DIR=/app/.torchxrayvision
      - MPLCONFIGDIR=/app/.matplotlib
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./data_exports:/app/data_exports
    restart: unless-stopped

  # Celery Beat for scheduled tasks
  celery-beat:
    build: .
    container_name: mcads_celery_beat
    entrypoint: []
    command: bash -c "
      while ! pg_isready -h db -p 5432 -U mcads_user; do sleep 2; done &&
      while ! redis-cli -h redis ping > /dev/null 2>&1; do sleep 2; done &&
      celery -A mcads_project beat -l info"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SECRET_KEY=mcads-production-key-2024-xray-deployment-server-secure-key-hashes
      - DEBUG=False
      - DB_NAME=mcads_db
      - DB_USER=mcads_user
      - DB_PASSWORD=mcads_secure_password_2024
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - TORCH_HOME=/app/.torch
      - TORCHXRAYVISION_CACHE_DIR=/app/.torchxrayvision
      - XRV_DATA_DIR=/app/.torchxrayvision
      - MPLCONFIGDIR=/app/.matplotlib
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: mcads_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mcads.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: