# Generated by Django 5.2 on 2025-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xrays/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('atelectasis', models.FloatField(blank=True, null=True)),
                ('cardiomegaly', models.FloatField(blank=True, null=True)),
                ('consolidation', models.FloatField(blank=True, null=True)),
                ('edema', models.FloatField(blank=True, null=True)),
                ('effusion', models.FloatField(blank=True, null=True)),
                ('emphysema', models.FloatField(blank=True, null=True)),
                ('fibrosis', models.FloatField(blank=True, null=True)),
                ('hernia', models.FloatField(blank=True, null=True)),
                ('infiltration', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('nodule', models.FloatField(blank=True, null=True)),
                ('pleural_thickening', models.FloatField(blank=True, null=True)),
                ('pneumonia', models.FloatField(blank=True, null=True)),
                ('pneumothorax', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
