# Generated by Django 5.2.4 on 2026-02-04 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Radiographer', 'Radiographer'), ('Technologist', 'Technologist'), ('Radiologist', 'Radiologist')], default='Radiographer', max_length=20)),
                ('hospital', models.CharField(default='VULSK', help_text='Hospital name for shared prediction history', max_length=100)),
                ('preferred_theme', models.CharField(choices=[('auto', 'System Default'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=10)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('lt', 'Lithuanian')], default='en', max_length=10)),
                ('dashboard_view', models.CharField(choices=[('grid', 'Grid View'), ('list', 'List View')], default='grid', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('processing_complete_notification', models.BooleanField(default=True)),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('patient_id', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('date_of_xray', models.DateField(blank=True, db_index=True, null=True)),
                ('additional_info', models.TextField(blank=True)),
                ('technologist_first_name', models.CharField(blank=True, max_length=100)),
                ('technologist_last_name', models.CharField(blank=True, max_length=100)),
                ('image', models.FileField(max_length=255, upload_to='xrays/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('image_format', models.CharField(blank=True, max_length=10)),
                ('image_size', models.CharField(blank=True, max_length=20)),
                ('image_resolution', models.CharField(blank=True, max_length=20)),
                ('image_date_created', models.DateTimeField(blank=True, null=True)),
                ('has_gradcam', models.BooleanField(default=False)),
                ('gradcam_visualization', models.CharField(blank=True, max_length=255, null=True)),
                ('gradcam_heatmap', models.CharField(blank=True, max_length=255, null=True)),
                ('gradcam_overlay', models.CharField(blank=True, max_length=255, null=True)),
                ('gradcam_target_class', models.CharField(blank=True, max_length=50, null=True)),
                ('has_pli', models.BooleanField(default=False)),
                ('pli_visualization', models.CharField(blank=True, max_length=255, null=True)),
                ('pli_overlay_visualization', models.CharField(blank=True, max_length=255, null=True)),
                ('pli_saliency_map', models.CharField(blank=True, max_length=255, null=True)),
                ('pli_target_class', models.CharField(blank=True, max_length=50, null=True)),
                ('atelectasis', models.FloatField(blank=True, null=True)),
                ('cardiomegaly', models.FloatField(blank=True, null=True)),
                ('consolidation', models.FloatField(blank=True, null=True)),
                ('edema', models.FloatField(blank=True, null=True)),
                ('effusion', models.FloatField(blank=True, null=True)),
                ('emphysema', models.FloatField(blank=True, null=True)),
                ('fibrosis', models.FloatField(blank=True, null=True)),
                ('hernia', models.FloatField(blank=True, null=True)),
                ('infiltration', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('nodule', models.FloatField(blank=True, null=True)),
                ('pleural_thickening', models.FloatField(blank=True, null=True)),
                ('pneumonia', models.FloatField(blank=True, null=True)),
                ('pneumothorax', models.FloatField(blank=True, null=True)),
                ('fracture', models.FloatField(blank=True, null=True)),
                ('lung_opacity', models.FloatField(blank=True, null=True)),
                ('enlarged_cardiomediastinum', models.FloatField(blank=True, null=True)),
                ('lung_lesion', models.FloatField(blank=True, null=True)),
                ('severity_level', models.IntegerField(blank=True, null=True)),
                ('requires_expert_review', models.BooleanField(default=False)),
                ('model_used', models.CharField(default='densenet', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xray_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_type', models.CharField(choices=[('gradcam', 'GRAD-CAM'), ('pli', 'Pixel-level Interpretability'), ('combined_gradcam', 'Combined'), ('combined_pli', 'Combined PLI'), ('segmentation', 'Anatomical Segmentation'), ('segmentation_combined', 'Combined Segmentation')], max_length=30)),
                ('target_pathology', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visualization_path', models.CharField(blank=True, max_length=255, null=True)),
                ('heatmap_path', models.CharField(blank=True, max_length=255, null=True)),
                ('overlay_path', models.CharField(blank=True, max_length=255, null=True)),
                ('saliency_path', models.CharField(blank=True, max_length=255, null=True)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('xray', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='xrayapp.xrayimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_used', models.CharField(max_length=50)),
                ('atelectasis', models.FloatField(blank=True, null=True)),
                ('cardiomegaly', models.FloatField(blank=True, null=True)),
                ('consolidation', models.FloatField(blank=True, null=True)),
                ('edema', models.FloatField(blank=True, null=True)),
                ('effusion', models.FloatField(blank=True, null=True)),
                ('emphysema', models.FloatField(blank=True, null=True)),
                ('fibrosis', models.FloatField(blank=True, null=True)),
                ('hernia', models.FloatField(blank=True, null=True)),
                ('infiltration', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('nodule', models.FloatField(blank=True, null=True)),
                ('pleural_thickening', models.FloatField(blank=True, null=True)),
                ('pneumonia', models.FloatField(blank=True, null=True)),
                ('pneumothorax', models.FloatField(blank=True, null=True)),
                ('fracture', models.FloatField(blank=True, null=True)),
                ('lung_opacity', models.FloatField(blank=True, null=True)),
                ('enlarged_cardiomediastinum', models.FloatField(blank=True, null=True)),
                ('lung_lesion', models.FloatField(blank=True, null=True)),
                ('severity_level', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_history', to=settings.AUTH_USER_MODEL)),
                ('xray', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_history', to='xrayapp.xrayimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_history', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='xrayapp.predictionhistory')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='saved_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', 'saved_at'], name='xrayapp_sav_user_id_d82a0e_idx'), models.Index(fields=['prediction_history', 'saved_at'], name='xrayapp_sav_predict_c4f875_idx')],
                'unique_together': {('user', 'prediction_history')},
            },
        ),
        migrations.AddConstraint(
            model_name='xrayimage',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='xrayimage_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='xrayimage',
            constraint=models.CheckConstraint(condition=models.Q(('severity_level__isnull', True), models.Q(('severity_level__gte', 1), ('severity_level__lte', 5)), _connector='OR'), name='xrayimage_severity_range'),
        ),
        migrations.AddIndex(
            model_name='visualizationresult',
            index=models.Index(fields=['xray', '-created_at'], name='xrayapp_vis_xray_id_9baecc_idx'),
        ),
        migrations.AddConstraint(
            model_name='visualizationresult',
            constraint=models.UniqueConstraint(fields=('xray', 'visualization_type', 'target_pathology'), name='unique_visualization_per_pathology'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['xray', '-created_at'], name='xrayapp_pre_xray_id_5c59a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='predictionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('severity_level__isnull', True), models.Q(('severity_level__gte', 1), ('severity_level__lte', 5)), _connector='OR'), name='predhistory_severity_range'),
        ),
    ]
