# Generated by Django 5.2 on 2025-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', 'add_gradcam_separate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayimage',
            name='gradcam_visualization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='pli_overlay_visualization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='pli_visualization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
