# Generated by Django 5.2.3 on 2025-06-24 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='xrayimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='filter_by_date_max',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='filter_by_date_min',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='filter_by_gender',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='filter_by_pathology',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='model_used',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='severity_level',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='atelectasis',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='cardiomegaly',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='consolidation',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='date_of_xray',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='edema',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='effusion',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='emphysema',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='enlarged_cardiomediastinum',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='fibrosis',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='fracture',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='gender',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='has_gradcam',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='has_pli',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='hernia',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='infiltration',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='lung_lesion',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='lung_opacity',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='mass',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='nodule',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='pleural_thickening',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='pneumonia',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='pneumothorax',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='processing_status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='severity_level',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='support_devices',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['user', 'created_at'], name='xrayapp_pre_user_id_2227df_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['model_used', 'created_at'], name='xrayapp_pre_model_u_c85311_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['filter_by_gender', 'created_at'], name='xrayapp_pre_filter__0b8110_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['filter_by_pathology', 'created_at'], name='xrayapp_pre_filter__417d69_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['severity_level', 'created_at'], name='xrayapp_pre_severit_460e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayimage',
            index=models.Index(fields=['user', 'uploaded_at'], name='xrayapp_xra_user_id_25ca4c_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayimage',
            index=models.Index(fields=['processing_status', 'uploaded_at'], name='xrayapp_xra_process_6fe6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayimage',
            index=models.Index(fields=['patient_id', 'date_of_xray'], name='xrayapp_xra_patient_5616d1_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayimage',
            index=models.Index(fields=['gender', 'date_of_birth'], name='xrayapp_xra_gender_187df1_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayimage',
            index=models.Index(fields=['severity_level', 'uploaded_at'], name='xrayapp_xra_severit_ef0c67_idx'),
        ),
    ]
