# Generated by Django 5.2 on 2025-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='fracture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='lung_opacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='support_devices',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
