# Generated by Django 5.2.4 on 2025-07-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hospital',
            field=models.CharField(db_index=True, default='VULSK', help_text='Hospital name for shared prediction history', max_length=100),
        ),
    ]
