# Generated by Django 5.2 on 2025-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0002_xrayimage_fracture_xrayimage_lung_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
