# Generated by Django 5.2.4 on 2025-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0002_userprofile_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='technologist_first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='technologist_last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
