# Generated by Django 5.2.4 on 2025-07-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0003_xrayimage_technologist_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_type', models.CharField(choices=[('gradcam', 'GRAD-CAM'), ('pli', 'Pixel-level Interpretability'), ('combined_gradcam', 'Combined GRAD-CAM'), ('combined_pli', 'Combined PLI')], db_index=True, max_length=20)),
                ('target_pathology', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visualization_path', models.CharField(blank=True, max_length=255, null=True)),
                ('heatmap_path', models.CharField(blank=True, max_length=255, null=True)),
                ('overlay_path', models.CharField(blank=True, max_length=255, null=True)),
                ('saliency_path', models.CharField(blank=True, max_length=255, null=True)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('xray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='xrayapp.xrayimage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['xray', 'visualization_type'], name='xrayapp_vis_xray_id_19cb28_idx'), models.Index(fields=['xray', 'target_pathology'], name='xrayapp_vis_xray_id_2ced55_idx'), models.Index(fields=['created_at'], name='xrayapp_vis_created_37ddbc_idx')],
                'constraints': [models.UniqueConstraint(fields=('xray', 'visualization_type', 'target_pathology'), name='unique_visualization_per_pathology')],
            },
        ),
    ]
