# Generated by Django 5.2 on 2025-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0003_xrayimage_processing_status_xrayimage_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='enlarged_cardiomediastinum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='lung_lesion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
