# Generated by Django 5.2.4 on 2025-07-16 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0004_visualizationresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prediction_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='xrayapp.predictionhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', 'saved_at'], name='xrayapp_sav_user_id_d82a0e_idx'), models.Index(fields=['prediction_history', 'saved_at'], name='xrayapp_sav_predict_c4f875_idx')],
                'unique_together': {('user', 'prediction_history')},
            },
        ),
    ]
