# Generated by Django 5.2 on 2025-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0004_xrayimage_enlarged_cardiomediastinum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='gradcam_target_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='gradcam_visualization',
            field=models.ImageField(blank=True, null=True, upload_to='interpretability/gradcam/'),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='has_gradcam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='has_pli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='pli_target_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='pli_visualization',
            field=models.ImageField(blank=True, null=True, upload_to='interpretability/pli/'),
        ),
    ]
