# Generated by Django 5.2.4 on 2025-07-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0005_add_saved_record_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='support_devices',
        ),
        migrations.RemoveField(
            model_name='xrayimage',
            name='support_devices',
        ),
    ]
