# Generated by Django 5.2 on 2025-05-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0005_xrayimage_gradcam_target_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='date_of_xray',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='patient_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(max_length=50)),
                ('filter_by_gender', models.CharField(blank=True, max_length=10)),
                ('filter_by_age_min', models.IntegerField(blank=True, null=True)),
                ('filter_by_age_max', models.IntegerField(blank=True, null=True)),
                ('filter_by_date_min', models.DateField(blank=True, null=True)),
                ('filter_by_date_max', models.DateField(blank=True, null=True)),
                ('filter_by_pathology', models.CharField(blank=True, max_length=50)),
                ('filter_by_pathology_threshold', models.FloatField(blank=True, null=True)),
                ('atelectasis', models.FloatField(blank=True, null=True)),
                ('cardiomegaly', models.FloatField(blank=True, null=True)),
                ('consolidation', models.FloatField(blank=True, null=True)),
                ('edema', models.FloatField(blank=True, null=True)),
                ('effusion', models.FloatField(blank=True, null=True)),
                ('emphysema', models.FloatField(blank=True, null=True)),
                ('fibrosis', models.FloatField(blank=True, null=True)),
                ('hernia', models.FloatField(blank=True, null=True)),
                ('infiltration', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('nodule', models.FloatField(blank=True, null=True)),
                ('pleural_thickening', models.FloatField(blank=True, null=True)),
                ('pneumonia', models.FloatField(blank=True, null=True)),
                ('pneumothorax', models.FloatField(blank=True, null=True)),
                ('fracture', models.FloatField(blank=True, null=True)),
                ('lung_opacity', models.FloatField(blank=True, null=True)),
                ('enlarged_cardiomediastinum', models.FloatField(blank=True, null=True)),
                ('lung_lesion', models.FloatField(blank=True, null=True)),
                ('support_devices', models.FloatField(blank=True, null=True)),
                ('xray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_history', to='xrayapp.xrayimage')),
            ],
        ),
    ]
