# Generated by Django 5.2 on 2025-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0006_xrayimage_additional_info_xrayimage_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='image_date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='image_format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='image_resolution',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='image_size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
