# Generated by Django 5.2.4 on 2025-07-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0006_remove_support_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='model_used',
            field=models.CharField(db_index=True, default='densenet', max_length=50),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='requires_expert_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualizationresult',
            name='visualization_type',
            field=models.CharField(choices=[('gradcam', 'GRAD-CAM'), ('pli', 'Pixel-level Interpretability'), ('combined_gradcam', 'Combined'), ('combined_pli', 'Combined PLI')], db_index=True, max_length=20),
        ),
    ]
