# Generated by Django 5.2.4 on 2025-11-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0007_xrayimage_model_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationresult',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visualizationresult',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualizationresult',
            name='visualization_type',
            field=models.CharField(choices=[('gradcam', 'GRAD-CAM'), ('pli', 'Pixel-level Interpretability'), ('combined_gradcam', 'Combined'), ('combined_pli', 'Combined PLI'), ('segmentation', 'Anatomical Segmentation'), ('segmentation_combined', 'Combined Segmentation')], db_index=True, max_length=30),
        ),
    ]
