# Generated by Django 5.2 on 2025-05-02 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0007_xrayimage_image_date_created_xrayimage_image_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_theme', models.CharField(choices=[('auto', 'System Default'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=10)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('lt', 'Lithuanian')], default='en', max_length=10)),
                ('dashboard_view', models.CharField(choices=[('grid', 'Grid View'), ('list', 'List View')], default='grid', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('processing_complete_notification', models.BooleanField(default=True)),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
