# Generated by Django 5.2 on 2025-05-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='severity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='severity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
