# Generated by Django 5.2.4 on 2026-01-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0008_visualizationresult_confidence_score_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='predictionhistory',
            name='xrayapp_pre_filter__0b8110_idx',
        ),
        migrations.RemoveIndex(
            model_name='predictionhistory',
            name='xrayapp_pre_filter__417d69_idx',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='filter_by_age_max',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='filter_by_age_min',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='filter_by_date_max',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='filter_by_date_min',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='filter_by_gender',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='filter_by_pathology',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='filter_by_pathology_threshold',
        ),
    ]
