# Generated by Django 5.2.4 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0009_remove_predictionhistory_xrayapp_pre_filter__0b8110_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='xrays/'),
        ),
    ]
