# Generated by Django 5.2 on 2025-05-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0009_predictionhistory_severity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='pli_overlay_visualization',
            field=models.ImageField(blank=True, null=True, upload_to='interpretability/pli/'),
        ),
    ]
