# Generated by Django 5.2.4 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xrayapp", "0010_alter_xrayimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xrayimage",
            name="image",
            field=models.FileField(max_length=255, upload_to="xrays/"),
        ),
    ]

