# Generated by Django 5.2 on 2025-05-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrayapp', '0010_xrayimage_pli_overlay_visualization'),
        ('xrayapp', 'add_pli_saliency_map'),
    ]

    operations = [
    ]
