"""
Django settings for mcads_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import environ
from typing import cast
from django.core.management.utils import get_random_secret_key

# Fix PyTorch CPU backend issues - must be set before torch import
os.environ['MKLDNN_ENABLED'] = '0'
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'

# Initialize environ
env = environ.Env(
    # Set default values
    DEBUG=(bool, True),  # Default to True for development
    SECRET_KEY=(str, ''.join([get_random_secret_key(), get_random_secret_key()[:20]])),  # Generate longer key
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),  # Default development hosts
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file if it exists
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Types resolved via Env defaults declared above
DEBUG: bool = cast(bool, env('DEBUG'))
ALLOWED_HOSTS: list[str] = cast(list[str], env('ALLOWED_HOSTS'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'csp',  # Content Security Policy
    'django_celery_beat',  # Celery beat scheduler
    'django_celery_results',  # Celery result backend
    'xrayapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'xrayapp.middleware.RateLimitMiddleware',
    'xrayapp.middleware.RoleBasedAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mcads_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcads_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MCADS uses PostgreSQL only (no fallback database backend).
#
# Supported env var sets:
# - DB_* (preferred): DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT
# - POSTGRES_* (Docker-friendly): POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
_db_name = os.environ.get('DB_NAME') or os.environ.get('POSTGRES_DB') or 'mcads_db'
_db_user = os.environ.get('DB_USER') or os.environ.get('POSTGRES_USER') or 'mcads_user'
_db_password = os.environ.get('DB_PASSWORD') or os.environ.get('POSTGRES_PASSWORD') or ''
_db_host = os.environ.get('DB_HOST') or os.environ.get('POSTGRES_HOST') or 'localhost'
_db_port = os.environ.get('DB_PORT') or os.environ.get('POSTGRES_PORT') or '5432'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _db_name,
        'USER': _db_user,
        'PASSWORD': _db_password,
        'HOST': _db_host,
        'PORT': _db_port,
        # Docker default: no TLS inside the private network.
        # Override with DB_SSLMODE if you use a managed/external Postgres.
        'OPTIONS': {'sslmode': os.environ.get('DB_SSLMODE', 'disable')},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Security settings for production
DEBUG = True # FORCE DEBUG FOR TESTING
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = not DEBUG  # Force HTTPS in production
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year for production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Respect HTTPS when behind a reverse proxy (Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Session security
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG  # Secure cookies for production
SESSION_COOKIE_SAMESITE = 'Strict'

# CSRF protection
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for AJAX requests
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for better AJAX support
CSRF_COOKIE_SECURE = not DEBUG  # Use secure cookies in production

# File upload security
#
# DICOM uploads are commonly larger than JPG/PNG. We allow larger request bodies,
# but keep the in-memory threshold modest so Django streams large files to disk.
# NOTE: Keep this aligned with Nginx `client_max_body_size`.
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB in-memory threshold
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB max request size
FILE_UPLOAD_PERMISSIONS = 0o644

# Logging configuration for security monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 10*1024*1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['security_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'xrayapp': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / 'logs'
os.makedirs(logs_dir, exist_ok=True)

# Cache configuration
# Use Redis if REDIS_CACHE_URL is provided; otherwise fall back to in-memory cache for development
_redis_cache_url = os.environ.get('REDIS_CACHE_URL')
if _redis_cache_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_cache_url,
            'TIMEOUT': 300,  # 5 minutes
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'mcads-local',
            'TIMEOUT': 300,
        }
    }

# Cache middleware (add to MIDDLEWARE for full page caching if needed)
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = 'mcads'

# Content Security Policy (django-csp 3.8 format)
# Serve all CSS/JS locally; keep CSP strict and simple.
CSP_DEFAULT_SRC = ("'self'",)
CSP_BASE_URI = ("'self'",)
CSP_CONNECT_SRC = ("'self'",)
CSP_FONT_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)
CSP_IMG_SRC = ("'self'", 'data:')
CSP_OBJECT_SRC = ("'none'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'",)
# Explicitly allow stylesheet <link>/<style> sources
CSP_STYLE_SRC_ELEM = ("'self'", "'unsafe-inline'",)

# Back-compat structure (has no effect for django-csp 3.8, retained for clarity)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'base-uri': ("'self'",),
        'connect-src': ("'self'",),
        'default-src': ("'self'",),
        'font-src': ("'self'",),
        'frame-ancestors': ("'none'",),
        'img-src': ("'self'", 'data:',),
        'object-src': ("'none'",),
        'script-src': ("'self'", "'unsafe-inline'",),
        'style-src': ("'self'", "'unsafe-inline'",),
    }
}

# Static files storage
#
# Django 5.x uses the `STORAGES["staticfiles"]` alias for static collection and
# URL generation. Keeping this explicit avoids relying on deprecated settings.
STORAGES = {
    # User uploads / media.
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Collected static assets.
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        )
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('lt', 'Lietuvių'),  # Lithuanian
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Language cookie settings
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = None  # Session cookie (expires when browser closes)
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = '/'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# Admin URL (keep secret)
ADMIN_URL = 'secure-admin-mcads-2024/'

# Rate limiting settings
RATELIMIT_MAX_ATTEMPTS = 5
RATELIMIT_LOCKOUT_DURATION = 300  # 5 minutes in seconds

# Celery Configuration
USE_CELERY = os.environ.get('USE_CELERY', '0') == '1'
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

# Celery task settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Task routing and worker settings
CELERY_TASK_ROUTES = {
    'xrayapp.tasks.*': {'queue': 'celery'},
}

# Worker settings
CELERY_WORKER_CONCURRENCY = 1  # Single worker for memory constrained environment
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_DISABLE_RATE_LIMITS = False

# Task execution settings
CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_TIME_LIMIT = 360  # 6 minutes
CELERY_TASK_ALWAYS_EAGER = False  # Set to True for testing without Celery

# Beat scheduler settings
CELERY_BEAT_SCHEDULE = {
    # Add scheduled tasks here if needed
}
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Test configuration
import sys
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    import tempfile
    # Use a temporary directory for media files during tests
    MEDIA_ROOT = tempfile.mkdtemp()
    
    # Disable Celery for tests
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
